services:
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker-gpu
    volumes:
      - .:/app
    command: sh -c "cd src && PRELOAD_MODEL=1 celery -A celery_app worker --loglevel=INFO --concurrency=4"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - image_vector_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: image_vector
    container_name: flower_monitoring-no-gpu
    ports:
      - "5555:5555"
    command: sh -c "cd src && celery -A celery_app flower --port=5555"
    depends_on:
      - celery
      - redis
    env_file:
      - .env
    networks:
      - image_vector_network
  


  redis:
    image: redis:latest
    container_name: redis_container
    volumes:
      - redis_data:/data
    ports:
      - "6389:6379"
    networks:
      - image_vector_network

  encoder_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encoder_api
    ports:
      - "8888:8888"
    command: sh -c "cd src && uvicorn embedding.api:app --host 0.0.0.0 --port 8888"
    env_file:
      - .env
    networks:
      - image_vector_network

  qdrant5M:
    image: qdrant/qdrant:latest
    container_name: qdrant_5M_container
    ports:
      - "6335:6333"
    volumes:
    
      - ./qdrant_storage:/qdrant/storage
    networks:
      - image_vector_network  

  qdrant1_5M:
    image: qdrant/qdrant:latest
    container_name: qdrant_1_5M_container
    ports:
      - "6331:6333"
    volumes:
      - ./qdrant_1_5M_storage:/qdrant/storage
    networks:
      - image_vector_network
  

networks:
  image_vector_network:
    driver: bridge

volumes:
  redis_data:

